site_name: MongoDB Guide
theme: 'material'
pages: 
  - 'Introduction': index.md
  - 'CRUD Operations':
    - 'Create': crud/create.md
    - 'Read': crud/read.md
    - 'Update': crud/update.md
    - 'Delete': crud/delete.md
  - 'Development':
    - 'Drivers': development/drivers.md
    - 'Schema design': development/schema_design.md
  - 'Management actions':
    - 'Common tasks': management_actions/common_tasks.md
    - 'Configuration files': management_actions/configuration_files.md
    - 'Replication': management_actions/replication.md
    - 'Sharding': management_actions/sharding.md
    - 'Statistics': management_actions/statistics.md
  - 'Security':
    - 'Encryption': security/encryption.md
    - 'Roles': security/roles.md
    - 'Auditing': security/auditing.md
    - 'Good practices': security/good_practices.md
  - 'Performance':
      - 'Indexes': performance/indexes.md
  - 'Deployment':
    - 'Common steps': deployment/common_steps.md
    - 'Good practices': deployment/good_practices.md
  - 'Tools': tools.md

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
extra:
  palette:
    primary: 'light green'
    accent: 'green'
  social:
    - type: 'github'
      link: 'https://github.com/Devlinked'
